services:
  api:
    ports:
      - "8083:3000"

  admin:
    build:
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:8083/api/v1
    ports:
      - "8081:3000"

  student:
    build:
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:8083/api/v1
    ports:
      - "8082:3000"
